version: '3'
services:
  # redis:
  #   image: redis:5.0
  #   container_name: broker
  #   expose:
  #     - 6379
  
  server:
    build: ./server
    command: 'npm start'
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3002:8080"
    environment:
      MYSQL_HOST: messagedb
      MYSQL_USER: root
      MYSQL_DB: messages
      MYSQL_PASSWORD: password
  
  messagedb:
    build: ./messagedb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3001:3306"
    environment:
       MYSQL_DATABASE: messages
       MYSQL_ROOT_PASSWORD: password

volumes:
    mysql_data: