version: '3'
services:
  client:
    build: ./client
    command: 'npm test'
    environment:
      CI: "true"
    

  server:
    build: ./server
    command: 'npm test'
    volumes:
      - ./server:/app
      - /app/node_modules/
    ports:
      - "3001:8080"
    environment:
      MYSQL_HOST: messagedb
      MYSQL_USER: root
      MYSQL_DB: messages
      MYSQL_PASSWORD: password
      NODE_ENV: development
      DOCKERIZE_VERSION: v0.6.1

  messagedb:
    build: ./messagedb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
       MYSQL_DATABASE: messages
       MYSQL_ROOT_PASSWORD: password
  
volumes:
  mysql_data: