version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install pip
          command: apk add --no-cache py-pip=9.0.0-r1
      - run:
          name: Install docker-compose
          command: pip install docker-compose==1.12.0
      - run:
          name: spin up db
          command: docker-compose -f ./docker-compose.test.yml up -d messagedb 
      - run:
          name: wait for db
          command: docker-compose -f ./docker-compose.test.yml run server ./wait-for-db.sh
      - run:
          name: Run server tests
          command: docker-compose -f ./docker-compose.test.yml run server
      - run:
          name: Run client tests
          command: docker-compose -f ./docker-compose.test.yml run client
      

