version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install alpine deps
          command: apk add py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
      - run:
          name: Install docker-compose
          command: pip install docker-compose
      - run:
          name: spin up db
          command: docker-compose -f ./circleci-compose.yml up -d messagedb 
      - run:
          name: wait for db
          command: docker-compose -f ./circleci-compose.yml run server ./wait-for-db.sh
      - run:
          name: Run server tests
          command: docker-compose -f ./circleci-compose.yml run server
      - run:
          name: Run client tests
          command: docker-compose -f ./circleci-compose.yml run client
      

